version: "3"

services:
  firelinks_frontend:
    build: 
      context: /frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true 
    tty: true
    volumes:
      - "./frontend:/app"